<?php

namespace AppBundle\Repository;

/**
 * CartItemProductAdditionItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartItemProductAdditionItemRepository extends \Doctrine\ORM\EntityRepository
{
}
