<?php

namespace AppBundle\Repository;

/**
 * CommissionStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissionStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
