<?php

namespace AppBundle\Repository;

/**
 * LocalBusinessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalBusinessRepository extends \Doctrine\ORM\EntityRepository
{
}
