<?php

namespace AppBundle\Repository;

/**
 * OpeningHourExtraordinaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpeningHourExtraordinaryRepository extends \Doctrine\ORM\EntityRepository
{
}
