<?php

namespace AppBundle\Repository;

/**
 * ProductAllergenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAllergenRepository extends \Doctrine\ORM\EntityRepository
{
}
