<?php

namespace AppBundle\Repository;

/**
 * ProductAdditionItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAdditionItemRepository extends \Doctrine\ORM\EntityRepository
{
}
