<?php

namespace AppBundle\Repository;

/**
 * ProductAdditionRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAdditionRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
