<?php

namespace AppBundle\Repository;

/**
 * ProductAdditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAdditionRepository extends \Doctrine\ORM\EntityRepository
{
}
