<?php

namespace AppBundle\Repository;

/**
 * ProductMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
