<?php

namespace AppBundle\Repository;

/**
 * ProductTakeoverTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTakeoverTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
