<?php

namespace AppBundle\Repository;

/**
 * ProductLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
